#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Key {
    Unknown = 0,

    // Printable keys
    Space,
    Apostrophe,
    Comma,
    Minus,
    Period,
    Slash,

    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,

    Semicolon,
    Equal,

    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,

    LeftBracket,
    Backslash,
    RightBracket,
    GraveAccent,
    World1,
    World2,

    // Function keys
    Escape,
    Enter,
    Tab,
    Backspace,
    Insert,
    Delete,
    Right,
    Left,
    Down,
    Up,
    PageUp,
    PageDown,
    Home,
    End,
    CapsLock,
    ScrollLock,
    NumLock,
    PrintScreen,
    Pause,

    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,

    // Keypad
    Keypad0,
    Keypad1,
    Keypad2,
    Keypad3,
    Keypad4,
    Keypad5,
    Keypad6,
    Keypad7,
    Keypad8,
    Keypad9,
    KeypadDecimal,
    KeypadDivide,
    KeypadMultiply,
    KeypadSubtract,
    KeypadAdd,
    KeypadEnter,
    KeypadEqual,

    // Modifiers
    LeftShift,
    LeftControl,
    LeftAlt,
    LeftSuper,
    RightShift,
    RightControl,
    RightAlt,
    RightSuper,
    Menu,

    Count,
}

pub const KEY_COUNT: usize = Key::Count as usize;

pub fn convert_key(key: glfw::Key) -> Option<Key> {
    match key {
        glfw::Key::Unknown => Some(Key::Unknown),

        glfw::Key::Space => Some(Key::Space),
        glfw::Key::Apostrophe => Some(Key::Apostrophe),
        glfw::Key::Comma => Some(Key::Comma),
        glfw::Key::Minus => Some(Key::Minus),
        glfw::Key::Period => Some(Key::Period),
        glfw::Key::Slash => Some(Key::Slash),

        glfw::Key::Num0 => Some(Key::Num0),
        glfw::Key::Num1 => Some(Key::Num1),
        glfw::Key::Num2 => Some(Key::Num2),
        glfw::Key::Num3 => Some(Key::Num3),
        glfw::Key::Num4 => Some(Key::Num4),
        glfw::Key::Num5 => Some(Key::Num5),
        glfw::Key::Num6 => Some(Key::Num6),
        glfw::Key::Num7 => Some(Key::Num7),
        glfw::Key::Num8 => Some(Key::Num8),
        glfw::Key::Num9 => Some(Key::Num9),

        glfw::Key::Semicolon => Some(Key::Semicolon),
        glfw::Key::Equal => Some(Key::Equal),

        glfw::Key::A => Some(Key::A),
        glfw::Key::B => Some(Key::B),
        glfw::Key::C => Some(Key::C),
        glfw::Key::D => Some(Key::D),
        glfw::Key::E => Some(Key::E),
        glfw::Key::F => Some(Key::F),
        glfw::Key::G => Some(Key::G),
        glfw::Key::H => Some(Key::H),
        glfw::Key::I => Some(Key::I),
        glfw::Key::J => Some(Key::J),
        glfw::Key::K => Some(Key::K),
        glfw::Key::L => Some(Key::L),
        glfw::Key::M => Some(Key::M),
        glfw::Key::N => Some(Key::N),
        glfw::Key::O => Some(Key::O),
        glfw::Key::P => Some(Key::P),
        glfw::Key::Q => Some(Key::Q),
        glfw::Key::R => Some(Key::R),
        glfw::Key::S => Some(Key::S),
        glfw::Key::T => Some(Key::T),
        glfw::Key::U => Some(Key::U),
        glfw::Key::V => Some(Key::V),
        glfw::Key::W => Some(Key::W),
        glfw::Key::X => Some(Key::X),
        glfw::Key::Y => Some(Key::Y),
        glfw::Key::Z => Some(Key::Z),

        glfw::Key::LeftBracket => Some(Key::LeftBracket),
        glfw::Key::Backslash => Some(Key::Backslash),
        glfw::Key::RightBracket => Some(Key::RightBracket),
        glfw::Key::GraveAccent => Some(Key::GraveAccent),
        glfw::Key::World1 => Some(Key::World1),
        glfw::Key::World2 => Some(Key::World2),

        glfw::Key::Escape => Some(Key::Escape),
        glfw::Key::Enter => Some(Key::Enter),
        glfw::Key::Tab => Some(Key::Tab),
        glfw::Key::Backspace => Some(Key::Backspace),
        glfw::Key::Insert => Some(Key::Insert),
        glfw::Key::Delete => Some(Key::Delete),
        glfw::Key::Right => Some(Key::Right),
        glfw::Key::Left => Some(Key::Left),
        glfw::Key::Down => Some(Key::Down),
        glfw::Key::Up => Some(Key::Up),
        glfw::Key::PageUp => Some(Key::PageUp),
        glfw::Key::PageDown => Some(Key::PageDown),
        glfw::Key::Home => Some(Key::Home),
        glfw::Key::End => Some(Key::End),
        glfw::Key::CapsLock => Some(Key::CapsLock),
        glfw::Key::ScrollLock => Some(Key::ScrollLock),
        glfw::Key::NumLock => Some(Key::NumLock),
        glfw::Key::PrintScreen => Some(Key::PrintScreen),
        glfw::Key::Pause => Some(Key::Pause),

        glfw::Key::F1 => Some(Key::F1),
        glfw::Key::F2 => Some(Key::F2),
        glfw::Key::F3 => Some(Key::F3),
        glfw::Key::F4 => Some(Key::F4),
        glfw::Key::F5 => Some(Key::F5),
        glfw::Key::F6 => Some(Key::F6),
        glfw::Key::F7 => Some(Key::F7),
        glfw::Key::F8 => Some(Key::F8),
        glfw::Key::F9 => Some(Key::F9),
        glfw::Key::F10 => Some(Key::F10),
        glfw::Key::F11 => Some(Key::F11),
        glfw::Key::F12 => Some(Key::F12),
        glfw::Key::F13 => Some(Key::F13),
        glfw::Key::F14 => Some(Key::F14),
        glfw::Key::F15 => Some(Key::F15),
        glfw::Key::F16 => Some(Key::F16),
        glfw::Key::F17 => Some(Key::F17),
        glfw::Key::F18 => Some(Key::F18),
        glfw::Key::F19 => Some(Key::F19),
        glfw::Key::F20 => Some(Key::F20),
        glfw::Key::F21 => Some(Key::F21),
        glfw::Key::F22 => Some(Key::F22),
        glfw::Key::F23 => Some(Key::F23),
        glfw::Key::F24 => Some(Key::F24),
        glfw::Key::F25 => Some(Key::F25),

        glfw::Key::Kp0 => Some(Key::Keypad0),
        glfw::Key::Kp1 => Some(Key::Keypad1),
        glfw::Key::Kp2 => Some(Key::Keypad2),
        glfw::Key::Kp3 => Some(Key::Keypad3),
        glfw::Key::Kp4 => Some(Key::Keypad4),
        glfw::Key::Kp5 => Some(Key::Keypad5),
        glfw::Key::Kp6 => Some(Key::Keypad6),
        glfw::Key::Kp7 => Some(Key::Keypad7),
        glfw::Key::Kp8 => Some(Key::Keypad8),
        glfw::Key::Kp9 => Some(Key::Keypad9),
        glfw::Key::KpDecimal => Some(Key::KeypadDecimal),
        glfw::Key::KpDivide => Some(Key::KeypadDivide),
        glfw::Key::KpMultiply => Some(Key::KeypadMultiply),
        glfw::Key::KpSubtract => Some(Key::KeypadSubtract),
        glfw::Key::KpAdd => Some(Key::KeypadAdd),
        glfw::Key::KpEnter => Some(Key::KeypadEnter),
        glfw::Key::KpEqual => Some(Key::KeypadEqual),

        glfw::Key::LeftShift => Some(Key::LeftShift),
        glfw::Key::LeftControl => Some(Key::LeftControl),
        glfw::Key::LeftAlt => Some(Key::LeftAlt),
        glfw::Key::LeftSuper => Some(Key::LeftSuper),
        glfw::Key::RightShift => Some(Key::RightShift),
        glfw::Key::RightControl => Some(Key::RightControl),
        glfw::Key::RightAlt => Some(Key::RightAlt),
        glfw::Key::RightSuper => Some(Key::RightSuper),
        glfw::Key::Menu => Some(Key::Menu),
    }
}